server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://strapi:1337/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Strapi Admin Panel and Assets
    location /admin {
        proxy_pass http://strapi:1337/admin;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /i18n/ {
        proxy_pass http://strapi:1337/i18n/;
    }

    location /content-manager/ {
        proxy_pass http://strapi:1337/content-manager/;
    }

    location /content-type-builder/ {
        proxy_pass http://strapi:1337/content-type-builder/;
    }

    location /upload/ {
        proxy_pass http://strapi:1337/upload/;
    }

    location /users-permissions/ {
        proxy_pass http://strapi:1337/users-permissions/;
    }
}
